careerinfo =[
{
    "CAREER": "SOFTWARE ENGINEER",
    "DESCRIPTION": "Designs, develops, tests, and maintains software applications and computer systems.",
    "Interest": ["PROGRAMMING", "TECHNOLOGY", "CODING"],
    "SKILLS": ["PYTHON", "PROBLEM SOLVING", "PROGRAMMING LANGUAGES"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS", "INFORMATION TECHNOLOGY"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH (CSE)", "B.E. COMPUTER ENGINEERING", "BCA"],
    "ENTRANCE EXAMS": ["JEE MAIN", "JEE ADVANCED", "BITSAT", "VITEEE", "SRMJEEE"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "DATA SCIENTIST",
    "DESCRIPTION": "Analyzes data to find patterns and helps organizations make better decisions using machine learning.",
    "Interest": ["DATA ANALYSIS", "MATHEMATICS", "ARTIFICIAL INTELLIGENCE"],
    "SKILLS": ["PYTHON", "STATISTICS", "MACHINE LEARNING"],
    "Subject": ["MATHEMATICS", "COMPUTER SCIENCE"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.TECH (AI/DS)", "B.SC DATA SCIENCE", "BCA"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT", "CUET", "VITEEE"],
    "MINIMUM PERCENTAGE": 80.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "DOCTOR",
    "DESCRIPTION": "Diagnoses illnesses, treats patients, and promotes health and well-being.",
    "Interest": ["BIOLOGY", "HELPING PEOPLE", "HEALTHCARE"],
    "SKILLS": ["COMMUNICATION", "CRITICAL THINKING"],
    "Subject": ["BIOLOGY", "CHEMISTRY", "PHYSICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "WITH BIOLOGY"],
    "AFTER 12TH DEGREE": ["MBBS", "BDS", "BAMS", "BHMS"],
    "ENTRANCE EXAMS": ["NEET UG"],
    "MINIMUM PERCENTAGE": 85.0,
    "Preferred Working Environment": "HOSPITAL"
},
{
    "CAREER": "MECHANICAL ENGINEER",
    "DESCRIPTION": "Designs, builds, and improves machines and mechanical systems.",
    "Interest": ["MACHINES", "DESIGN", "TECHNOLOGY"],
    "SKILLS": ["PROBLEM SOLVING", "CAD"],
    "Subject": ["PHYSICS", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH MECHANICAL", "B.E. MECHANICAL"],
    "ENTRANCE EXAMS": ["JEE MAIN", "JEE ADVANCED", "BITSAT", "VITEEE"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "FACTORY"
},
{
    "CAREER": "CIVIL ENGINEER",
    "DESCRIPTION": "Plans and supervises the construction of buildings, roads, and bridges.",
    "Interest": ["CONSTRUCTION", "DESIGN", "INFRASTRUCTURE"],
    "SKILLS": ["AUTOCAD", "PROJECT MANAGEMENT"],
    "Subject": ["PHYSICS", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH CIVIL", "B.E. CIVIL"],
    "ENTRANCE EXAMS": ["JEE MAIN", "JEE ADVANCED", "BITSAT", "VITEEE"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "CONSTRUCTION SITE"
},
{
    "CAREER": "TEACHER",
    "DESCRIPTION": "Educates students and helps them develop knowledge and skills.",
    "Interest": ["TEACHING", "LEARNING", "HELPING OTHERS"],
    "SKILLS": ["COMMUNICATION", "PATIENCE"],
    "Subject": ["ENGLISH", "MATHEMATICS"],
    "Education Level": "BACHELOR'S DEGREE",
    "AFTER 12TH DEGREE": ["B.A.", "B.SC", "B.COM", "B.ED (AFTER GRADUATION)"],
    "ENTRANCE EXAMS": ["CUET"],
    "MINIMUM PERCENTAGE": 60.0,
    "Preferred Working Environment": "SCHOOL"
},
{
    "CAREER": "GRAPHIC DESIGNER",
    "DESCRIPTION": "Creates logos, posters, and digital designs using creative software.",
    "Interest": ["ART", "CREATIVITY", "DESIGN"],
    "SKILLS": ["ADOBE PHOTOSHOP", "CREATIVITY"],
    "Subject": ["ARTS", "COMPUTER SCIENCE"],
    "Education Level": "12TH",
    "STREAM": ["ARTS", "COMMERCE", "SCIENCE"],
    "AFTER 12TH DEGREE": ["B.DES", "BFA", "B.SC GRAPHIC DESIGN"],
    "ENTRANCE EXAMS": ["UCEED", "NID DAT", "NIFT ENTRANCE", "CUET"],
    "MINIMUM PERCENTAGE": 55.0,
    "Preferred Working Environment": "OFFICE"
},
{
    "CAREER": "CYBERSECURITY ANALYST",
    "DESCRIPTION": "Protects organizations from cyber attacks and security threats.",
    "Interest": ["TECHNOLOGY", "SECURITY", "NETWORKING"],
    "SKILLS": ["NETWORKING", "PYTHON", "LINUX"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC CYBER SECURITY"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT", "CUET", "VITEEE"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "CHARTERED ACCOUNTANT",
    "DESCRIPTION": "Manages accounting, taxation, auditing, and financial planning.",
    "Interest": ["FINANCE", "ACCOUNTING", "BUSINESS"],
    "SKILLS": ["ACCOUNTING", "EXCEL", "ANALYTICAL THINKING"],
    "Subject": ["ACCOUNTANCY", "ECONOMICS", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["COMMERCE"],
    "AFTER 12TH DEGREE": ["B.COM", "CA FOUNDATION"],
    "ENTRANCE EXAMS": ["CA FOUNDATION"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "OFFICE"
},
{
    "CAREER": "LAWYER",
    "DESCRIPTION": "Provides legal advice and represents clients in court.",
    "Interest": ["LAW", "DEBATE", "JUSTICE"],
    "SKILLS": ["COMMUNICATION", "RESEARCH", "CRITICAL THINKING"],
    "Subject": ["POLITICAL SCIENCE", "ENGLISH", "HISTORY"],
    "Education Level": "12TH",
    "STREAM": ["ARTS"],
    "AFTER 12TH DEGREE": ["BA LLB", "BBA LLB", "B.COM LLB"],
    "ENTRANCE EXAMS": ["CLAT", "AILET", "SLAT", "LSAT INDIA"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "COURT"
},

{
    "CAREER": "WEB DEVELOPER",
    "DESCRIPTION": "Builds and maintains websites and web applications.",
    "Interest": ["PROGRAMMING", "WEB TECHNOLOGY", "DESIGN"],
    "SKILLS": ["HTML", "CSS", "JAVASCRIPT"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE", "B.SC COMPUTER SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 60.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "MOBILE APP DEVELOPER",
    "DESCRIPTION": "Develops applications for Android and iOS devices.",
    "Interest": ["PROGRAMMING", "TECHNOLOGY", "MOBILE APPS"],
    "SKILLS": ["JAVA", "KOTLIN", "FLUTTER"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "AI ENGINEER",
    "DESCRIPTION": "Develops artificial intelligence systems and intelligent applications.",
    "Interest": ["ARTIFICIAL INTELLIGENCE", "PROGRAMMING", "MATHEMATICS"],
    "SKILLS": ["PYTHON", "MACHINE LEARNING", "DEEP LEARNING"],
    "Subject": ["MATHEMATICS", "COMPUTER SCIENCE"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH AI", "B.TECH CSE (AI)", "B.SC AI"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT", "VITEEE"],
    "MINIMUM PERCENTAGE": 80.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "CLOUD ENGINEER",
    "DESCRIPTION": "Designs and manages cloud computing infrastructure.",
    "Interest": ["CLOUD COMPUTING", "TECHNOLOGY", "NETWORKING"],
    "SKILLS": ["AWS", "LINUX", "PYTHON"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "DEVOPS ENGINEER",
    "DESCRIPTION": "Automates software deployment and manages development infrastructure.",
    "Interest": ["AUTOMATION", "PROGRAMMING", "CLOUD COMPUTING"],
    "SKILLS": ["LINUX", "DOCKER", "PYTHON"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "NETWORK ENGINEER",
    "DESCRIPTION": "Designs, installs, and maintains computer networks for organizations.",
    "Interest": ["NETWORKING", "TECHNOLOGY", "PROBLEM SOLVING"],
    "SKILLS": ["NETWORK CONFIGURATION", "ROUTERS", "LINUX"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC INFORMATION TECHNOLOGY"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET", "VITEEE"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "DATABASE ADMINISTRATOR",
    "DESCRIPTION": "Manages, secures, and maintains organizational databases.",
    "Interest": ["DATABASES", "TECHNOLOGY", "DATA MANAGEMENT"],
    "SKILLS": ["SQL", "DATABASE MANAGEMENT", "PROBLEM SOLVING"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE", "B.SC COMPUTER SCIENCE"],
    "ENTRANCE EXAMS": ["CUET", "JEE MAIN"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "UI/UX DESIGNER",
    "DESCRIPTION": "Designs user-friendly interfaces and improves user experience for digital products.",
    "Interest": ["DESIGN", "CREATIVITY", "TECHNOLOGY"],
    "SKILLS": ["FIGMA", "ADOBE XD", "CREATIVITY"],
    "Subject": ["COMPUTER SCIENCE", "ARTS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE", "ARTS"],
    "AFTER 12TH DEGREE": ["B.DES", "BCA", "B.SC DESIGN"],
    "ENTRANCE EXAMS": ["UCEED", "NID DAT", "CUET"],
    "MINIMUM PERCENTAGE": 60.0,
    "Preferred Working Environment": "OFFICE"
},
{
    "CAREER": "GAME DEVELOPER",
    "DESCRIPTION": "Develops video games for computers, consoles, and mobile devices.",
    "Interest": ["PROGRAMMING", "GAMING", "CREATIVITY"],
    "SKILLS": ["C++", "UNITY", "PROBLEM SOLVING"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC GAME DEVELOPMENT"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "BLOCKCHAIN DEVELOPER",
    "DESCRIPTION": "Builds secure decentralized applications and blockchain solutions.",
    "Interest": ["PROGRAMMING", "CRYPTOGRAPHY", "TECHNOLOGY"],
    "SKILLS": ["SOLIDITY", "PYTHON", "SMART CONTRACTS"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "ROBOTICS ENGINEER",
    "DESCRIPTION": "Designs, develops, and tests robotic systems for industries.",
    "Interest": ["ROBOTICS", "ENGINEERING", "AUTOMATION"],
    "SKILLS": ["PYTHON", "C++", "ELECTRONICS"],
    "Subject": ["PHYSICS", "MATHEMATICS", "COMPUTER SCIENCE"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH ROBOTICS", "B.TECH MECHATRONICS"],
    "ENTRANCE EXAMS": ["JEE MAIN", "JEE ADVANCED", "BITSAT"],
    "MINIMUM PERCENTAGE": 80.0,
    "Preferred Working Environment": "LABORATORY"
},
{
    "CAREER": "IOT ENGINEER",
    "DESCRIPTION": "Develops smart devices that communicate through the Internet of Things.",
    "Interest": ["ELECTRONICS", "PROGRAMMING", "TECHNOLOGY"],
    "SKILLS": ["EMBEDDED C", "PYTHON", "ARDUINO"],
    "Subject": ["PHYSICS", "MATHEMATICS", "COMPUTER SCIENCE"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH ECE", "B.TECH IOT"],
    "ENTRANCE EXAMS": ["JEE MAIN", "VITEEE"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "LABORATORY"
},
{
    "CAREER": "EMBEDDED SYSTEMS ENGINEER",
    "DESCRIPTION": "Designs software and hardware for embedded electronic devices.",
    "Interest": ["ELECTRONICS", "PROGRAMMING", "MICROCONTROLLERS"],
    "SKILLS": ["C", "EMBEDDED SYSTEMS", "DEBUGGING"],
    "Subject": ["PHYSICS", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH ECE", "B.TECH ELECTRICAL"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "LABORATORY"
},
{
    "CAREER": "SYSTEM ADMINISTRATOR",
    "DESCRIPTION": "Maintains servers, operating systems, and IT infrastructure.",
    "Interest": ["COMPUTERS", "NETWORKING", "TECHNOLOGY"],
    "SKILLS": ["LINUX", "WINDOWS SERVER", "NETWORKING"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE"],
    "ENTRANCE EXAMS": ["CUET", "JEE MAIN"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "QA ENGINEER",
    "DESCRIPTION": "Tests software applications to ensure quality and reliability.",
    "Interest": ["TESTING", "TECHNOLOGY", "PROBLEM SOLVING"],
    "SKILLS": ["MANUAL TESTING", "AUTOMATION TESTING", "SELENIUM"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE"],
    "ENTRANCE EXAMS": ["CUET", "JEE MAIN"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "CLOUD ARCHITECT",
    "DESCRIPTION": "Designs and manages cloud infrastructure and cloud-based applications.",
    "Interest": ["CLOUD COMPUTING", "TECHNOLOGY", "NETWORKING"],
    "SKILLS": ["AWS", "AZURE", "LINUX"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC COMPUTER SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT", "CUET"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "MACHINE LEARNING ENGINEER",
    "DESCRIPTION": "Builds machine learning models for prediction and automation.",
    "Interest": ["ARTIFICIAL INTELLIGENCE", "DATA", "PROGRAMMING"],
    "SKILLS": ["PYTHON", "MACHINE LEARNING", "STATISTICS"],
    "Subject": ["MATHEMATICS", "COMPUTER SCIENCE"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH AI", "B.TECH CSE", "B.SC DATA SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT", "CUET"],
    "MINIMUM PERCENTAGE": 80.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "COMPUTER VISION ENGINEER",
    "DESCRIPTION": "Develops AI systems that analyze and understand images and videos.",
    "Interest": ["ARTIFICIAL INTELLIGENCE", "IMAGES", "PROGRAMMING"],
    "SKILLS": ["PYTHON", "OPENCV", "DEEP LEARNING"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH AI", "B.TECH CSE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT"],
    "MINIMUM PERCENTAGE": 80.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "NLP ENGINEER",
    "DESCRIPTION": "Builds AI systems that understand and process human language.",
    "Interest": ["ARTIFICIAL INTELLIGENCE", "LANGUAGE", "PROGRAMMING"],
    "SKILLS": ["PYTHON", "NATURAL LANGUAGE PROCESSING", "MACHINE LEARNING"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS", "ENGLISH"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH AI", "B.TECH CSE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "BITSAT"],
    "MINIMUM PERCENTAGE": 80.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "DATA ENGINEER",
    "DESCRIPTION": "Builds data pipelines and manages large-scale data systems.",
    "Interest": ["DATA", "PROGRAMMING", "DATABASES"],
    "SKILLS": ["SQL", "PYTHON", "BIG DATA"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC DATA SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "BIG DATA ENGINEER",
    "DESCRIPTION": "Manages and processes massive datasets for business insights.",
    "Interest": ["DATA", "TECHNOLOGY", "PROGRAMMING"],
    "SKILLS": ["HADOOP", "SPARK", "PYTHON"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "B.SC DATA SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 75.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "BUSINESS INTELLIGENCE ANALYST",
    "DESCRIPTION": "Analyzes business data and creates reports to support decision-making.",
    "Interest": ["BUSINESS", "DATA ANALYSIS", "TECHNOLOGY"],
    "SKILLS": ["SQL", "POWER BI", "EXCEL"],
    "Subject": ["MATHEMATICS", "COMPUTER SCIENCE", "ECONOMICS"],
    "Education Level": "BACHELOR'S DEGREE",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.COM", "B.SC DATA SCIENCE"],
    "ENTRANCE EXAMS": ["CUET"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "OFFICE"
},
{
    "CAREER": "PENETRATION TESTER",
    "DESCRIPTION": "Finds security vulnerabilities in systems through ethical hacking techniques.",
    "Interest": ["CYBER SECURITY", "NETWORKING", "TECHNOLOGY"],
    "SKILLS": ["LINUX", "PYTHON", "PENETRATION TESTING"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.SC CYBER SECURITY", "BCA", "B.TECH CSE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "ETHICAL HACKER",
    "DESCRIPTION": "Tests computer systems for security weaknesses and helps prevent cyber attacks.",
    "Interest": ["CYBER SECURITY", "HACKING", "NETWORKING"],
    "SKILLS": ["LINUX", "PYTHON", "NETWORK SECURITY"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE", "B.SC CYBER SECURITY"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "SECURITY ENGINEER",
    "DESCRIPTION": "Designs and implements security systems to protect digital infrastructure.",
    "Interest": ["CYBER SECURITY", "TECHNOLOGY", "NETWORKING"],
    "SKILLS": ["FIREWALLS", "NETWORK SECURITY", "LINUX"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC CYBER SECURITY"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 70.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "SOFTWARE TEST ENGINEER",
    "DESCRIPTION": "Tests software applications to identify bugs and ensure quality before release.",
    "Interest": ["TESTING", "TECHNOLOGY", "PROBLEM SOLVING"],
    "SKILLS": ["SELENIUM", "MANUAL TESTING", "AUTOMATION TESTING"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC COMPUTER SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET", "VITEEE"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "FULL STACK DEVELOPER",
    "DESCRIPTION": "Develops both frontend and backend components of web applications.",
    "Interest": ["PROGRAMMING", "WEB DEVELOPMENT", "TECHNOLOGY"],
    "SKILLS": ["HTML", "CSS", "JAVASCRIPT", "PYTHON"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE", "B.SC COMPUTER SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "FRONTEND DEVELOPER",
    "DESCRIPTION": "Creates interactive and responsive user interfaces for websites and web applications.",
    "Interest": ["WEB DESIGN", "PROGRAMMING", "CREATIVITY"],
    "SKILLS": ["HTML", "CSS", "JAVASCRIPT", "REACT"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 60.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "BACKEND DEVELOPER",
    "DESCRIPTION": "Develops server-side applications, APIs, and databases for software systems.",
    "Interest": ["PROGRAMMING", "DATABASES", "TECHNOLOGY"],
    "SKILLS": ["PYTHON", "JAVA", "SQL"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["B.TECH CSE", "BCA", "B.SC COMPUTER SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 65.0,
    "Preferred Working Environment": "INDOORS"
},
{
    "CAREER": "COMPUTER PROGRAMMER",
    "DESCRIPTION": "Writes, tests, and maintains computer programs and software applications.",
    "Interest": ["PROGRAMMING", "TECHNOLOGY", "PROBLEM SOLVING"],
    "SKILLS": ["PYTHON", "JAVA", "C++"],
    "Subject": ["COMPUTER SCIENCE", "MATHEMATICS"],
    "Education Level": "12TH",
    "STREAM": ["SCIENCE", "COMMERCE"],
    "AFTER 12TH DEGREE": ["BCA", "B.TECH CSE", "B.SC COMPUTER SCIENCE"],
    "ENTRANCE EXAMS": ["JEE MAIN", "CUET"],
    "MINIMUM PERCENTAGE": 60.0,
    "Preferred Working Environment": "INDOORS"
},

]